# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QoveryCli < Formula
  desc "Deploy modern application in seconds"
  homepage "https://docs.qovery.com"
  version "0.67.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.67.1/qovery-cli_0.67.1_darwin_arm64.tar.gz"
      sha256 "9ae004ad7ea8d4a548b373dc9ccd9beab0ed13f67859bc26d44bb82e92a757d4"

      def install
        bin.install "qovery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.67.1/qovery-cli_0.67.1_darwin_amd64.tar.gz"
      sha256 "47649af17ec5994299b5bfd61dbd5e1b52fda3a41782270ecb5d677d72a97582"

      def install
        bin.install "qovery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.67.1/qovery-cli_0.67.1_linux_arm64.tar.gz"
      sha256 "27075e086f4f6ec2069ab5f01d10ab8b778cfdb7da2b9d04def23326a93c35ac"

      def install
        bin.install "qovery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.67.1/qovery-cli_0.67.1_linux_amd64.tar.gz"
      sha256 "d569806f9683c9d641e959b83d43dc6152ca9099bb1778fd61dd26002e981fef"

      def install
        bin.install "qovery"
      end
    end
  end
end
