# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QoveryCli < Formula
  desc "Deploy modern application in seconds"
  homepage "https://docs.qovery.com"
  version "1.171.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/qovery-cli/releases/download/v1.171.3/qovery-cli_1.171.3_darwin_amd64.tar.gz"
      sha256 "df685336058404610e45c473f675757fd7bc52efd926e075ea338520d216abfb"

      define_method(:install) do
        bin.install "qovery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qovery/qovery-cli/releases/download/v1.171.3/qovery-cli_1.171.3_darwin_arm64.tar.gz"
      sha256 "98208bf7aca78d7b799b33654b9f74089fb3fa256f05576a0d525e4566bab9ec"

      define_method(:install) do
        bin.install "qovery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qovery/qovery-cli/releases/download/v1.171.3/qovery-cli_1.171.3_linux_amd64.tar.gz"
      sha256 "140fffb36c9c38de9c4e30afe9d5c0ec4abbbead1d007f2cc936dd9af078b72e"
      define_method(:install) do
        bin.install "qovery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qovery/qovery-cli/releases/download/v1.171.3/qovery-cli_1.171.3_linux_arm64.tar.gz"
      sha256 "5b903f329d301f2b38616b07c0df6ce8d5e9f418b6aff151d63766f25ac8d3e7"
      define_method(:install) do
        bin.install "qovery"
      end
    end
  end
end
