# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qovery < Formula
  desc "Deploy modern application in seconds"
  homepage "https://docs.qovery.com"
  version "0.41.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.41.4/qovery-cli_0.41.4_darwin_amd64.tar.gz"
      sha256 "c74da808fd15c158367b0dfd47b33ef308a7dbf775080a8003b04bec8b189020"

      def install
        bin.install "qovery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.41.4/qovery-cli_0.41.4_darwin_arm64.tar.gz"
      sha256 "b2858b85c69243f8fce70198631fbbda72992034663c592bbf5be109771616af"

      def install
        bin.install "qovery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.41.4/qovery-cli_0.41.4_linux_arm64.tar.gz"
      sha256 "895a0253de4892d1f6079a09427dc980df35f2854a9492616746cdebc1e5210b"

      def install
        bin.install "qovery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/qovery-cli/releases/download/v0.41.4/qovery-cli_0.41.4_linux_amd64.tar.gz"
      sha256 "4bb24e8d0fd1baea69e2eb2432c1eb18217793cb6dfa055cf6f4b8f8d00c89b1"

      def install
        bin.install "qovery"
      end
    end
  end
end
